language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - 7
  - hhvm
  
before_script: 
  - yes '' | pecl -q install -f mongo-1.2.12 && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --dev

matrix:
  allow_failures:
    - php: hhvm
    - php: 7
